version: '3.9'
services:
  main:
    build:
      context: ./docker
      tags:
        - automatisch/automatisch
      network: host
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - HOST=localhost
      - PROTOCOL=http
      - PORT=3000
      - APP_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=automatisch
      - POSTGRES_USERNAME=automatisch_user
      - POSTGRES_PASSWORD=automatisch_password
      - ENCRYPTION_KEY=automatisch_encryption_key
      - APP_SECRET_KEY=automatisch_app_secret_key
    volumes:
      - automatisch_storage:/automatisch/storage
  worker:
    build:
      context: ./docker
      network: host
      tags:
        - automatisch/automatisch
    depends_on:
      - main
    environment:
      - APP_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=automatisch
      - POSTGRES_USERNAME=automatisch_user
      - POSTGRES_PASSWORD=automatisch_password
      - ENCRYPTION_KEY=automatisch_encryption_key
      - APP_SECRET_KEY=automatisch_app_secret_key
      - WORKER=true
    volumes:
      - automatisch_storage:/automatisch/storage
  postgres:
    image: 'postgres:14.5'
    environment:
      - POSTGRES_DB=automatisch
      - POSTGRES_USER=automatisch_user
      - POSTGRES_PASSWORD=automatisch_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: 'redis:7.0.4'
    volumes:
      - redis_data:/data
volumes:
  automatisch_storage:
  postgres_data:
  redis_data:

